#ifndef TODOC_CHANGELOG_H
#define TODOC_CHANGELOG_H

#include <stddef.h>

/* The full CHANGELOG.md content embedded at build time. Generated by
 * scripts/embed_changelog.sh into src/changelog_data.c. */
extern const char *changelog_data;
extern const size_t changelog_data_len;

/* Print the section for the latest version (the first '## [X.Y.Z]'
 * heading in the embedded data). */
void changelog_print_latest(void);

/* Print one specific version. Accepts "0.5.0" or "v0.5.0". Returns 0
 * on hit, non-zero if the version is not in the embedded data. */
int changelog_print_version(const char *version);

/* Print every version section newer than `since` (exclusive lower
 * bound, semver-compared on the X.Y.Z form). Returns 0 if at least
 * one section was printed, non-zero otherwise. */
int changelog_print_since(const char *since);

/* Print the entire embedded changelog verbatim. */
void changelog_print_all(void);

/* Print just version names + dates, newest first, one per line. */
void changelog_list_versions(void);

#endif
